// Generated by gencpp from file sushant/BonusResponse.msg
// DO NOT EDIT!


#ifndef SUSHANT_MESSAGE_BONUSRESPONSE_H
#define SUSHANT_MESSAGE_BONUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sushant
{
template <class ContainerAllocator>
struct BonusResponse_
{
  typedef BonusResponse_<ContainerAllocator> Type;

  BonusResponse_()
    : out(0)  {
    }
  BonusResponse_(const ContainerAllocator& _alloc)
    : out(0)  {
  (void)_alloc;
    }



   typedef int32_t _out_type;
  _out_type out;





  typedef boost::shared_ptr< ::sushant::BonusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sushant::BonusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct BonusResponse_

typedef ::sushant::BonusResponse_<std::allocator<void> > BonusResponse;

typedef boost::shared_ptr< ::sushant::BonusResponse > BonusResponsePtr;
typedef boost::shared_ptr< ::sushant::BonusResponse const> BonusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sushant::BonusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sushant::BonusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sushant

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sushant::BonusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sushant::BonusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sushant::BonusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sushant::BonusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sushant::BonusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sushant::BonusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sushant::BonusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bbbbb4259d2725c3ce6331761b71c6ab";
  }

  static const char* value(const ::sushant::BonusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbbbbb4259d2725c3ULL;
  static const uint64_t static_value2 = 0xce6331761b71c6abULL;
};

template<class ContainerAllocator>
struct DataType< ::sushant::BonusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sushant/BonusResponse";
  }

  static const char* value(const ::sushant::BonusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sushant::BonusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 out\n\
";
  }

  static const char* value(const ::sushant::BonusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sushant::BonusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.out);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BonusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sushant::BonusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sushant::BonusResponse_<ContainerAllocator>& v)
  {
    s << indent << "out: ";
    Printer<int32_t>::stream(s, indent + "  ", v.out);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUSHANT_MESSAGE_BONUSRESPONSE_H
