// Generated by gencpp from file sushant/Bonus.msg
// DO NOT EDIT!


#ifndef SUSHANT_MESSAGE_BONUS_H
#define SUSHANT_MESSAGE_BONUS_H

#include <ros/service_traits.h>


#include <sushant/BonusRequest.h>
#include <sushant/BonusResponse.h>


namespace sushant
{

struct Bonus
{

typedef BonusRequest Request;
typedef BonusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Bonus
} // namespace sushant


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sushant::Bonus > {
  static const char* value()
  {
    return "4cb0d890bc6d9d096c24937d23485ba6";
  }

  static const char* value(const ::sushant::Bonus&) { return value(); }
};

template<>
struct DataType< ::sushant::Bonus > {
  static const char* value()
  {
    return "sushant/Bonus";
  }

  static const char* value(const ::sushant::Bonus&) { return value(); }
};


// service_traits::MD5Sum< ::sushant::BonusRequest> should match 
// service_traits::MD5Sum< ::sushant::Bonus > 
template<>
struct MD5Sum< ::sushant::BonusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sushant::Bonus >::value();
  }
  static const char* value(const ::sushant::BonusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sushant::BonusRequest> should match 
// service_traits::DataType< ::sushant::Bonus > 
template<>
struct DataType< ::sushant::BonusRequest>
{
  static const char* value()
  {
    return DataType< ::sushant::Bonus >::value();
  }
  static const char* value(const ::sushant::BonusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sushant::BonusResponse> should match 
// service_traits::MD5Sum< ::sushant::Bonus > 
template<>
struct MD5Sum< ::sushant::BonusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sushant::Bonus >::value();
  }
  static const char* value(const ::sushant::BonusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sushant::BonusResponse> should match 
// service_traits::DataType< ::sushant::Bonus > 
template<>
struct DataType< ::sushant::BonusResponse>
{
  static const char* value()
  {
    return DataType< ::sushant::Bonus >::value();
  }
  static const char* value(const ::sushant::BonusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUSHANT_MESSAGE_BONUS_H
