// Generated by gencpp from file sushant/Calculate.msg
// DO NOT EDIT!


#ifndef SUSHANT_MESSAGE_CALCULATE_H
#define SUSHANT_MESSAGE_CALCULATE_H

#include <ros/service_traits.h>


#include <sushant/CalculateRequest.h>
#include <sushant/CalculateResponse.h>


namespace sushant
{

struct Calculate
{

typedef CalculateRequest Request;
typedef CalculateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Calculate
} // namespace sushant


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sushant::Calculate > {
  static const char* value()
  {
    return "4f9050e81d07f2b4cef4589399b1dcb1";
  }

  static const char* value(const ::sushant::Calculate&) { return value(); }
};

template<>
struct DataType< ::sushant::Calculate > {
  static const char* value()
  {
    return "sushant/Calculate";
  }

  static const char* value(const ::sushant::Calculate&) { return value(); }
};


// service_traits::MD5Sum< ::sushant::CalculateRequest> should match 
// service_traits::MD5Sum< ::sushant::Calculate > 
template<>
struct MD5Sum< ::sushant::CalculateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::sushant::Calculate >::value();
  }
  static const char* value(const ::sushant::CalculateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::sushant::CalculateRequest> should match 
// service_traits::DataType< ::sushant::Calculate > 
template<>
struct DataType< ::sushant::CalculateRequest>
{
  static const char* value()
  {
    return DataType< ::sushant::Calculate >::value();
  }
  static const char* value(const ::sushant::CalculateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sushant::CalculateResponse> should match 
// service_traits::MD5Sum< ::sushant::Calculate > 
template<>
struct MD5Sum< ::sushant::CalculateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::sushant::Calculate >::value();
  }
  static const char* value(const ::sushant::CalculateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::sushant::CalculateResponse> should match 
// service_traits::DataType< ::sushant::Calculate > 
template<>
struct DataType< ::sushant::CalculateResponse>
{
  static const char* value()
  {
    return DataType< ::sushant::Calculate >::value();
  }
  static const char* value(const ::sushant::CalculateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUSHANT_MESSAGE_CALCULATE_H
