// Generated by gencpp from file sushant/Calculate2Request.msg
// DO NOT EDIT!


#ifndef SUSHANT_MESSAGE_CALCULATE2REQUEST_H
#define SUSHANT_MESSAGE_CALCULATE2REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sushant
{
template <class ContainerAllocator>
struct Calculate2Request_
{
  typedef Calculate2Request_<ContainerAllocator> Type;

  Calculate2Request_()
    : a(0.0)
    , op()  {
    }
  Calculate2Request_(const ContainerAllocator& _alloc)
    : a(0.0)
    , op(_alloc)  {
  (void)_alloc;
    }



   typedef float _a_type;
  _a_type a;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _op_type;
  _op_type op;





  typedef boost::shared_ptr< ::sushant::Calculate2Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sushant::Calculate2Request_<ContainerAllocator> const> ConstPtr;

}; // struct Calculate2Request_

typedef ::sushant::Calculate2Request_<std::allocator<void> > Calculate2Request;

typedef boost::shared_ptr< ::sushant::Calculate2Request > Calculate2RequestPtr;
typedef boost::shared_ptr< ::sushant::Calculate2Request const> Calculate2RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sushant::Calculate2Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sushant::Calculate2Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sushant

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sushant::Calculate2Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sushant::Calculate2Request_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sushant::Calculate2Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sushant::Calculate2Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sushant::Calculate2Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sushant::Calculate2Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sushant::Calculate2Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "23aa64df06170e290a9ed08838611b10";
  }

  static const char* value(const ::sushant::Calculate2Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x23aa64df06170e29ULL;
  static const uint64_t static_value2 = 0x0a9ed08838611b10ULL;
};

template<class ContainerAllocator>
struct DataType< ::sushant::Calculate2Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sushant/Calculate2Request";
  }

  static const char* value(const ::sushant::Calculate2Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sushant::Calculate2Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 a\n\
string op\n\
";
  }

  static const char* value(const ::sushant::Calculate2Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sushant::Calculate2Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.a);
      stream.next(m.op);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Calculate2Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sushant::Calculate2Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sushant::Calculate2Request_<ContainerAllocator>& v)
  {
    s << indent << "a: ";
    Printer<float>::stream(s, indent + "  ", v.a);
    s << indent << "op: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.op);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUSHANT_MESSAGE_CALCULATE2REQUEST_H
