// Generated by gencpp from file sushant/Calculate2.msg
// DO NOT EDIT!


#ifndef SUSHANT_MESSAGE_CALCULATE2_H
#define SUSHANT_MESSAGE_CALCULATE2_H

#include <ros/service_traits.h>


#include <sushant/Calculate2Request.h>
#include <sushant/Calculate2Response.h>


namespace sushant
{

struct Calculate2
{

typedef Calculate2Request Request;
typedef Calculate2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Calculate2
} // namespace sushant


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::sushant::Calculate2 > {
  static const char* value()
  {
    return "e7673e4ea221df947a4d6bd8795746a2";
  }

  static const char* value(const ::sushant::Calculate2&) { return value(); }
};

template<>
struct DataType< ::sushant::Calculate2 > {
  static const char* value()
  {
    return "sushant/Calculate2";
  }

  static const char* value(const ::sushant::Calculate2&) { return value(); }
};


// service_traits::MD5Sum< ::sushant::Calculate2Request> should match 
// service_traits::MD5Sum< ::sushant::Calculate2 > 
template<>
struct MD5Sum< ::sushant::Calculate2Request>
{
  static const char* value()
  {
    return MD5Sum< ::sushant::Calculate2 >::value();
  }
  static const char* value(const ::sushant::Calculate2Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::sushant::Calculate2Request> should match 
// service_traits::DataType< ::sushant::Calculate2 > 
template<>
struct DataType< ::sushant::Calculate2Request>
{
  static const char* value()
  {
    return DataType< ::sushant::Calculate2 >::value();
  }
  static const char* value(const ::sushant::Calculate2Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::sushant::Calculate2Response> should match 
// service_traits::MD5Sum< ::sushant::Calculate2 > 
template<>
struct MD5Sum< ::sushant::Calculate2Response>
{
  static const char* value()
  {
    return MD5Sum< ::sushant::Calculate2 >::value();
  }
  static const char* value(const ::sushant::Calculate2Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::sushant::Calculate2Response> should match 
// service_traits::DataType< ::sushant::Calculate2 > 
template<>
struct DataType< ::sushant::Calculate2Response>
{
  static const char* value()
  {
    return DataType< ::sushant::Calculate2 >::value();
  }
  static const char* value(const ::sushant::Calculate2Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SUSHANT_MESSAGE_CALCULATE2_H
