// Generated by gencpp from file sushant/Calculate2Response.msg
// DO NOT EDIT!


#ifndef SUSHANT_MESSAGE_CALCULATE2RESPONSE_H
#define SUSHANT_MESSAGE_CALCULATE2RESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sushant
{
template <class ContainerAllocator>
struct Calculate2Response_
{
  typedef Calculate2Response_<ContainerAllocator> Type;

  Calculate2Response_()
    : res(0.0)  {
    }
  Calculate2Response_(const ContainerAllocator& _alloc)
    : res(0.0)  {
  (void)_alloc;
    }



   typedef float _res_type;
  _res_type res;





  typedef boost::shared_ptr< ::sushant::Calculate2Response_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sushant::Calculate2Response_<ContainerAllocator> const> ConstPtr;

}; // struct Calculate2Response_

typedef ::sushant::Calculate2Response_<std::allocator<void> > Calculate2Response;

typedef boost::shared_ptr< ::sushant::Calculate2Response > Calculate2ResponsePtr;
typedef boost::shared_ptr< ::sushant::Calculate2Response const> Calculate2ResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sushant::Calculate2Response_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sushant::Calculate2Response_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sushant

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sushant::Calculate2Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sushant::Calculate2Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sushant::Calculate2Response_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sushant::Calculate2Response_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sushant::Calculate2Response_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sushant::Calculate2Response_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sushant::Calculate2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9d9130b17056d2aca7996ffac46d67a0";
  }

  static const char* value(const ::sushant::Calculate2Response_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9d9130b17056d2acULL;
  static const uint64_t static_value2 = 0xa7996ffac46d67a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::sushant::Calculate2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sushant/Calculate2Response";
  }

  static const char* value(const ::sushant::Calculate2Response_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sushant::Calculate2Response_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 res\n\
";
  }

  static const char* value(const ::sushant::Calculate2Response_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sushant::Calculate2Response_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.res);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Calculate2Response_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sushant::Calculate2Response_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sushant::Calculate2Response_<ContainerAllocator>& v)
  {
    s << indent << "res: ";
    Printer<float>::stream(s, indent + "  ", v.res);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SUSHANT_MESSAGE_CALCULATE2RESPONSE_H
