(cl:defpackage sushant-srv
  (:use )
  (:export
   "BONUS"
   "<BONUS-REQUEST>"
   "BONUS-REQUEST"
   "<BONUS-RESPONSE>"
   "BONUS-RESPONSE"
   "CALCULATE"
   "<CALCULATE-REQUEST>"
   "CALCULATE-REQUEST"
   "<CALCULATE-RESPONSE>"
   "CALCULATE-RESPONSE"
   "CALCULATE2"
   "<CALCULATE2-REQUEST>"
   "CALCULATE2-REQUEST"
   "<CALCULATE2-RESPONSE>"
   "CALCULATE2-RESPONSE"
  ))

